---

- name: Find the venv site-packages path
  command: python -c 'import site; print site.getsitepackages()[-1]'
  register: site_packages

- name: Ensure the site-packages directory exists
  file:
      path: "{{ site_packages.stdout }}"
      state: "directory"

- name: Create the .pth hook for coverage of the module
  copy:
      dest: "{{ site_packages.stdout }}/ansible_coverage.pth"
      content: "import coverage; coverage.process_startup()"