---

- include: process-module.yaml
  with_fileglob:
      - "{{ base_dir }}/library/bigip_*.py"
  loop_control:
      loop_var: f5_module_filename

# This cannot be inside of the files loop (which, as a consequence
# makes the overall role slower) because of the way that coverage works
#
# For example, upon the first run, the 'coverage combine' command will
# merge all of the .coverage files.
#
# On following runs, the tasks looking for filenames to replace in the
# coverage file, causing the same index to exist multiple times. When
# coverage tries to iterate over the keys, only the last key will be
# evaluated, so the whole set of coverage will be off.
#
# For example, running in parallel produces keys that look like this
#
#    !coverage.py: This is a private format, don't read it directly!
#    {
#      "arcs": {
#          "/p...e/var/f...s/jc/9d1...m45/T/ansible_rZUTVv/ansible_module_bigip_vlan.py":
#              [[-136, 137],....
#          ],
#          "/p...e/var/f...s/jc/9d1...m45/T/ansible_jhhs8v/ansible_module_bigip_vlan.py":
#              [[-143, 187],....
#          ]
#          ...
#
# The renaming task makes all of these look like this
#
#    !coverage.py: This is a private format, don't read it directly!
#    {
#      "arcs": {
#          "/Users/trupp/src/f5-ansible/library/bigip_vlan.py":
#              [[-136, 137],....
#          ],
#          "/Users/trupp/src/f5-ansible/library/bigip_vlan.py":
#              [[-143, 187],....
#          ]
#          ...
- name: Combine coverage files
  shell: "coverage combine cache/coverage/"
  when: toggle == 'off'
  args:
      chdir: "{{ base_dir|abspath }}"
      executable: "/bin/bash"
