---

- name: Create some module shorthand variables
  set_fact:
      module_full_path: "{{ playbook_dir + '/../library/' + f5_module + '.py' }}"

- name: Replace the name of the module in the coverage includes
  lineinfile:
      insertafter: "include ="
      regexp: "(MODULE_NAME|{{ f5_module }}\\*)"
      line: "    *ansible_module_{{ f5_module }}*"
      state: "present"
      dest: "{{ base_dir|abspath }}/.coveragerc"
  when: toggle == 'on'
  run_once: true

- name: Replace cache name in coverage file with module location
  replace:
      dest: "{{ item|abspath }}"
      regexp: '"([A-Za-z0-9_\./\\-]*{{ f5_module }}.py)"'
      replace: '"{{ module_full_path|abspath }}"'
  when: toggle == 'off'
  with_fileglob:
      - "{{ coverage_dir|abspath }}/.coverage.*"

- name: Combine coverage files
  shell: "coverage combine cache/coverage/"
  when: toggle == 'off'
  args:
      chdir: "{{ base_dir|abspath }}"
      executable: "/bin/bash"
  run_once: true

- name: Replace the name of the module to match original
  lineinfile:
      regexp: "\\*ansible_module_{{ f5_module }}\\*"
      line: "    *{{ f5_module }}*"
      state: "present"
      dest: "{{ base_dir|abspath }}/.coveragerc"
  when: toggle == 'off'