---

- name: Set some convenience facts for later usage
  set_fact:
      module_current: "{{ f5_module_filename|basename|splitext|first }}"

- name: Create some module shorthand variables
  set_fact:
      module_full_path: "{{ playbook_dir + '/../library/' + module_current + '.py' }}"

- name: Include tasks to enable coverage if requested
  include: "process-module-on.yaml"
  when: toggle == 'on'

- name: Include tasks to disable coverage if requested
  include: "process-module-off.yaml"
  when: toggle == 'off'