---

- name: Set NTP server
  bigip_device_ntp:
      ntp_server: "{{ ntp_server }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set NTP server
  assert:
      that:
          - result|changed

- name: Set NTP server - Idempotent check
  bigip_device_ntp:
      ntp_server: "{{ ntp_server }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Set NTP server - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete NTP server
  bigip_device_ntp:
      ntp_server: "{{ ntp_server }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete NTP server
  assert:
      that:
          - result|changed

- name: Delete NTP server - Idempotent check
  bigip_device_ntp:
      ntp_server: "{{ ntp_server }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Delete NTP server - Idempotent check
  assert:
      that:
          - not result|changed

- name: Set NTP server list
  bigip_device_ntp:
      ntp_servers: "{{ ntp_servers }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Set NTP server list
  assert:
      that:
          - result|changed

- name: Set NTP server list - Idempotent check
  bigip_device_ntp:
      ntp_servers: "{{ ntp_servers }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Set NTP server list - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete NTP server list
  bigip_device_ntp:
      ntp_servers: "{{ ntp_servers }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Assert Delete NTP server list
  assert:
      that:
          - result|changed

- name: Delete NTP server list - Idempotent check
  bigip_device_ntp:
      ntp_servers: "{{ ntp_servers }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Set NTP server list - Idempotent check
  assert:
      that:
          - not result|changed

- name: Delete missing NTP server
  bigip_device_ntp:
      ntp_servers: "{{ missing_server }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Delete missing NTP server
  assert:
      that:
          - not result|changed

- name: Delete missing NTP server list
  bigip_device_ntp:
      ntp_servers: "{{ missing_servers }}"
      password: "{{ bigip_password }}"
      server: "{{ inventory_hostname }}"
      server_port: "{{ bigip_port }}"
      state: "absent"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  register: result

- name: Delete missing NTP server list
  assert:
      that:
          - not result|changed