---

# Test the bigiq_license_pool_member module
#
# Running this playbook assumes that you have a BIG-IP installation at the
# ready to receive the commands issued in this Playbook.
#
# This module will run tests against a BIG-IP host to verify that the
# bigiq_license_pool_member module behaves as expected.
#
# Usage:
#
#    ansible-playbook -i notahost, playbooks/bigiq_license_pool_member.yaml
#
# Examples:
#
#    Run all tests on the bigiq_license_pool_member module
#
#    ansible-playbook -i notahost, playbooks/bigiq_license_pool_member.yaml
#
# Tested platforms:
#
#    - NA
#

- name: Test the bigiq_license_pool_member module
  hosts: f5-test
  connection: local

  roles:
      - bigiq_license_pool_member
